export const getPackageJson = (projectName, isTypescript, database) => {
  const commonScripts = {
    "start": "node src/index.js",
    "dev": "nodemon src/index.js"
  };

  const tsScripts = {
    "start": "tsx src/index.ts",
    "dev": "tsx watch src/index.ts",
    "build": "tsc"
  };

  const dependencies = {
    "express": "^4.18.2",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "helmet": "^7.1.0",
    "morgan": "^1.10.0"
  };

  if (database === 'MongoDB (Mongoose)') {
    dependencies["mongoose"] = "^8.0.3";
  } else if (database === 'PostgreSQL (Prisma)') {
    dependencies["@prisma/client"] = "^5.7.1";
  }

  const devDependencies = isTypescript ? {
    "typescript": "^5.3.3",
    "tsx": "^4.7.0",
    "@types/node": "^20.10.6",
    "@types/express": "^4.17.21",
    "@types/cors": "^2.8.17",
    "@types/morgan": "^1.9.9"
  } : {
    "nodemon": "^3.0.2"
  };

  if (isTypescript && database === 'MongoDB (Mongoose)') {
    devDependencies["@types/mongoose"] = "^5.11.97";
  }

  if (database === 'PostgreSQL (Prisma)') {
    devDependencies["prisma"] = "^5.7.1";
  }

  return JSON.stringify({
    name: projectName,
    version: "1.0.0",
    description: "Express.js application generated by set-it-up",
    main: isTypescript ? "src/index.ts" : "src/index.js",
    type: "module",
    scripts: isTypescript ? tsScripts : commonScripts,
    dependencies,
    devDependencies,
    keywords: [],
    author: "",
    license: "ISC"
  }, null, 2);
};

export const getTsConfig = () => {
  return JSON.stringify({
    "compilerOptions": {
      "target": "es2020",
      "module": "esnext",
      "moduleResolution": "node",
      "outDir": "./dist",
      "rootDir": "./src",
      "strict": true,
      "esModuleInterop": true,
      "skipLibCheck": true,
      "forceConsistentCasingInFileNames": true
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules"]
  }, null, 2);
};
